[project]
name = "day-2-classwork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kosionyia", email = "onyiakosisochi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "uvicorn>=0.52.4",
]

[project.scripts]
day-2-classwork = "day_2_classwork:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
