[project]
name = "swift-arrow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kosionyia", email = "onyiakosisochi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
]

[project.scripts]
swift-arrow = "swift_arrow:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
